### PR TITLE
Added Requisition Hook Guidance

### PR DESCRIPTION
**Pull request by CanYumusak**
## Background
When setting up a full requsition hook, I struggled (longer than I would like to admit) to make the hook run in the docker container. The reason for my struggle was missing tools in the docker container such as bash, cuRL and so on. I decided to fix the shebang and write up a guide to make this easier for people after me.

## Example Hook for LogSnag
```bash
#!/bin/sh
reqURL=$2

wget --header 'Content-Type: application/json' \
     --header 'Authorization: Bearer <my logsnag token>' \
     --post-data "{\"project\":\"<my project>\",\"channel\":\"<my channel>\",\"event\":\"Confirm requisition URL\",\"description\":\"${reqURL}\",\"icon\":\"❤️\",\"notify\":true}" \
     'https://api.logsnag.com/v1/log'#
```

### CODE REVIEW

**Review by martinohansen — APPROVED** [review]
Thank you!

**Comment by martinohansen** [comment]
@CanYumusak do you want to add the example LogSnag hook as a file before I merge this?

**Comment by CanYumusak** [comment]
> @CanYumusak do you want to add the example LogSnag hook as a file before I merge this? 

Sure, give me a sec

**Comment by CanYumusak** [comment]
> @CanYumusak do you want to add the example LogSnag hook as a file before I merge this?

Done! ☑️

**Review by martinohansen — APPROVED** [review]

**Comment by hpernu** [comment]
> ## Background
> 
> When setting up a full requsition hook, I struggled (longer than I would like to admit) to make the hook run in the docker container. The reason for my struggle was missing tools in the docker container such as bash, cuRL and so on. I decided to fix the shebang and write up a guide to make this easier for people after me.

My point exactly why this might not work so well in docker. You got it to work for example purposes but for somebody who  wants to do something else, they might face similar issues. Of course, you can do your own Docker image based on current one which is what I often end up doing.

Not to mention the permission issues related to files, if the script creates any. I actually earlier made a PR to update the README so that there would be options of running ynabber as a regular user in the example, but @martinohansen declined that. This easily becomes even more complicated and I've worked with docker a lot (in fact, daily).

Good that the option is there, though.

**Pull request merged**
