### PR TITLE
Use creditor or debtor name as payee

### PR DESCRIPTION
**Pull request by hpernu**
Instead of modified memo, use creditor/debtor name as the payee.

This may/may not be desirable for all people - the jury is still out. 
However, tt least here in Finland with the banks I have access to, memo is typically either empty or excessively verbose and contains no usable information for Payee. Creditor/debtor contains the name money is sent to/received from. This is most often directly usable as Payee.

### CODE REVIEW

**Comment by martinohansen** [comment]
This is related to this: https://github.com/martinohansen/ynabber/issues/10

It looks like every bank has a potentially different set of fields with valuable information that can be mapped to `memo` or other fields in YNAB. I don't think we're going to make it work for everyone with a hardcoded set of fields, we need to implement some kind of map that can be configured by the user.

**Comment by hpernu** [comment]
Yes, this is possible although I think on Finland the payee is clearly 
in creditorName or debtorName always. I think that is their intended 
purpose looking at what they contain and what the field name looks like.

However, that does not mean every bank operates in that way.

What kind of data are you seeing in other places to make unstructured 
data a candidate for payee?

It is certainly not at all useful as payee here. In fact, the data used 
for memo typically contains just the message, if any, sent/received with 
the transaction. This definitely different from payee and memo is most 
often empty.

To even begin to properly address this,
we would need example Nordigen json replies from a multitude of banks 
with the personal information removed. I think the information could be 
removed with a script.

I could provide mine from a couple of Finnish banks and can get some 
more from Finland.
Finnish banks are notoriously rigorous in many ways and generally follow 
rules to the letter even to a fault. I think most banks would try to 
bend the PSD2 to force people to use less open solutions so I think the 
situation in Finland is more conformant than in most countries.

For now, I need ynabber to use the creditorName/debtorName for Payee. 
Unstructruted data is useless for this and usually empty. In one 
instance, it is also horribly long and actually crashes Ynabber(due to 
error response from YNAB API) even if only used for memo. I am working 
on a solution to trim memo separately. That is needed anyway to trim 
down overly verbose data(YNAB has a 200 character limit).

In 13.10.2022 10.30, Martin Hansen wrote:

**Comment by hpernu** [comment]
Would the following logic work?

- use creditorName if it is available
- use debitorName if it is available
- use memo through payeestrip if it results in non-empty field
- something else?

Or are the debitor/creditorNames completely bogus in your previous data? If they are just empty, this should still work for all current users.

**Comment by hpernu** [comment]
Made some more changes, namely:
- uses memo as basis for payee as previously but overrides with creditor or debtor name if available
- truncates excessively long payees (this was observed at least in a single case where the memo was very long as well)

**Comment by martinohansen** [comment]
I agree, using the creditor and debitor names makes sense if you reason from the naming. I just checked the output from my bank and it looks like this:

```
2022/10/14 15:41:21 Account transactions received from nordigen: {Transactions:{Booked:[{TransactionId:REDACTED EntryReference: BookingDate:2022-08-01 ValueDate:2022-08-01 TransactionAmount:{Amount:REDACTED Currency:DKK} CreditorName:2000 CreditorAccount:{Iban:REDACTED} UltimateCreditor: DebtorName: DebtorAccount:{Iban:} UltimateDebtor: RemittanceInformationUnstructured:REDACTED RemittanceInformationUnstructuredArray:[] BankTransactionCode:}] Pending:[]}}
```

Even tho what you suggest makes sense I would prefer not to make any breaking changes and implement a map so the user can override how the fields are mapped to YNAB.

**Comment by hpernu** [comment]
I understand this although, in this particular case, a straightforward map does not work as the name is either on creditor/debtor(but not both) depending whether money was sent/received. There would need to be two maps, one for send and one for receive. What is more the current generation of payee from unstructured data is not straightforward mapping either.

For my purposes, I need to absolutely use the creditorName/debtorName but can, of course, maintain it on a separate fork.
How many people actually rely on current behavior and would it break for them?
We could have a poll. I do not know whether Github has such an option.

**Comment by martinohansen** [comment]
@hpernu how about using the BankID to determine which field to use? We could have a fallback method but use what we know works for the given bank?

**Comment by hpernu** [comment]
You mean hardcoded inside the go code or did you have something more configurable in mind?

It still begs the question what should be the default.
There are literally thousands of bankids and we really can't go coding them all. I've only tested with two Finnish banks and can possibly test with one more. But still we don't have test material and cannot trust them to remain constant. We'd have to assume something.

I am betting the debitor/creditor name is more likely to be payee in general but extracting it from memo is the backwards compatible way. Whether this is important depends on you and on how many people actually use this code.

**Comment by martinohansen** [comment]
@hpernu I made an attempt to fix it here: https://github.com/martinohansen/ynabber/pull/18 

Let me know what you think and if it solves your issue.

**Pull request closed without merging**
