### PR TITLE
Clean and shorten memo if necessary

### PR DESCRIPTION
**Pull request by hpernu**
Convert consequtive spaces to single one. This has been observerd at least on occasions on my accounts - a very long memo with several consequtive and unnecessary spaces.

Also truncate memo if it is over YNAB limit. Without these some transaction may/will result in error and the whole import set fails.

### CODE REVIEW

**Comment by martinohansen** [comment]
Good catch, the code looks good. But we should move it into the YNAB writer instead as its not really related to Nordigan: https://github.com/martinohansen/ynabber/blob/main/writer/ynab/ynab.go

And while we're at it, if you want, we should properly also move this code into the writer: https://github.com/martinohansen/ynabber/blob/b8fb63e18f74e47fb604854d5ef9722bd1c346f4/ynabber.go#L57-L67

**Comment by hpernu** [comment]
A similar treatment needs to be done for the payee except the limit there is 100 characters. I am not sure whether the consecutive space removal is desirable there. Probably, as it is pointless to have extra spaces on text fields.

I see what you mean on the location. Yes, logically, in a way it would correctly go on YNAB writer side.
On the other hand Nordigen reader is not well isolated either so we could argue that it has to format the structure members to be compatible with the writer. So far, the Nordigen side of this is still very YNAB oriented as it does not completely rely on opaque interface.

But its your call - this is your code after all. I just make patches which come up on my use cases. :) If you're of the opinion that these things should be moved to the writer side then so be it.

Shall I redo this to be on the writer side instead with possibly the similar addition for payee?

**Comment by martinohansen** [comment]
> A similar treatment needs to be done for the payee except the limit there is 100 characters. I am not sure whether the consecutive space removal is desirable there. Probably, as it is pointless to have extra spaces on text fields.
> 
> 
> 
> I see what you mean on the location. Yes, logically, in a way it would correctly go on YNAB writer side.
> 
> On the other hand Nordigen reader is not well isolated either so we could argue that it has to format the structure members to be compatible with the writer. So far, the Nordigen side of this is still very YNAB oriented as it does not completely rely on opaque interface.
> 
> 
> 
> But its your call - this is your code after all. I just make patches which come up on my use cases. :) If you're of the opinion that these things should be moved to the writer side then so be it.
> 
> 
> 
> Shall I redo this to be on the writer side instead with possibly the similar addition for payee?
> 
> 

Yes lets move it to the writer and get it merged.

Thanks for helping out with this, I appreciate it ✌️

**Comment by hpernu** [comment]
A new solution in progress but can you explain to me what is the purpose of all this stuff:
payee, err := v.Payee.Parsed(cfg.YNAB.PayeeStrip)

I.e. what the parsing is supposed to actually do?

**Comment by martinohansen** [comment]
> A new solution in progress but can you explain to me what is the purpose of all this stuff:
> 
> payee, err := v.Payee.Parsed(cfg.YNAB.PayeeStrip)
> 
> 
> 
> I.e. what the parsing is supposed to actually do?
> 
> 

Sure, so my bank only provides me with a single field containing the transaction message. That field also contains the date of the transaction, amount, and other bloat words which makes no sense to keep in the Payee name.

The `cfg.YNAB.PayeeStrip` contains a list of words to strip from the payee.

For example, to makes this: `VISA the 15/11 Foo 10 EUR` into this: `Foo`. 

If I remember correctly the current implementation strips numbers and the words passed by the user.

We could make this more generic by allowing the user to pass in the whole regex value?

**Comment by martinohansen** [comment]
Closed by https://github.com/martinohansen/ynabber/issues/20

**Pull request closed without merging**
